version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  node:
    build:
      context: node
    image: gostavok/entrega-node:latest
    container_name: node
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./node:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
  
  nginx:
    build:
      context: ./nginx
    image: gostavok/entrega-nginx:latest
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  node-network:
    driver: bridge